import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import AuthListener from "./components/AuthListener";


export const metadata: Metadata = {
  title: "Summarist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AuthListener />
        {children}
        </Providers>
      </body>
    </html>
  );
}
